# Generated by Django 6.0 on 2025-12-10 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_movies',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='movies.movie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='movies.movie'),
        ),
    ]
